### ISSUE TITLE
Could you share the source code for the example please?

### ISSUE THREAD

**Issue by amite** [asciidisco/grunt-patternprimer#2]

**Comment by stevebritton** [comment]
Hey @amite , you can find the patterns here:

https://github.com/adactio/Pattern-Primer

**Comment by amite** [comment]
Thank you

—

**Comment by stevebritton** [comment]
Also, if you're interested, I included Sass into the project here:
https://github.com/stevebritton/grunt-patternprimer

**Comment by amite** [comment]
Oh Cool. btw this project of yours finally got me taking grunt seriously :)
once I recognized the use case for it.

**Comment by stevebritton** [comment]
Actually, I cannot take credit for the project, I simply added Sass to it.  But yeah, Grunt is pretty sweet, I've been using it a lot lately.

**Comment by asciidisco** [comment]
I assume that I can close the issue?!
@stevebritton Would you like to send an PR for the README linking your fork with 1 or 2 sentences describing it?

**Comment by stevebritton** [comment]
@asciidisco A little late this, but just sent the PR.
