### ISSUE TITLE
Index option fails

### ISSUE THREAD

**Issue by getdave** [asciidisco/grunt-patternprimer#3]
I'm trying to use the `index` option to specify a custom `index.html` template. However it doesn't appear to be picking this up. 

My config:

``` js
// Pattern library
        patternprimer: {
            options: {
                wwwroot: 'prototype',
                src: 'prototype/source/patterns',
                dest: 'prototype/build',
                css: ['source/css/master.css'],
                index: 'prototype/source/index.html'
            },
            live: {
                ports: [7020, 7030],
            },
            snapshot: {
                snapshot: true
            }
        },
```

I believe you are using `index` and `frame` interchangeably which could be the issue.

https://github.com/asciidisco/grunt-patternprimer/blob/master/tasks/patternprimer.js#L147

In addition the replacement of `{{css}}` with a css file doesn't work on custom `index.html` templates either.

**Comment by asciidisco** [comment]
Fixed in v.0.1.1, al your observations where correct by the way.
Thanks for pointing this out in so much details.

**Comment by getdave** [comment]
@asciidisco Not a problem at all. Glad you managed to get this fixed. Great work!
